### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by ptrdiff**
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Vasar007%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/21951872%3Fv%3D4%22%7D%2C%20%22https%3A//github.com/ptrdiff%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/33400860%3Fv%3D4%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robot-lab/tinkoff-optimization-of-procurement/pull/22%23issuecomment-414140653%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222018-08-19T16%3A55%3A55Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/21951872%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Vasar007%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222018-08-19T16%3A57%3A49Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/33400860%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ptrdiff%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222018-08-19T16%3A58%3A05Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars1.githubusercontent.com/u/33400860%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/ptrdiff%22%7D%7D%2C%20%7B%22body%22%3A%20%22%5Cud83d%5Cudc4d%20%22%2C%20%22created_at%22%3A%20%222018-08-19T17%3A01%3A26Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars3.githubusercontent.com/u/21951872%3Fv%3D4%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Vasar007%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/robot-lab/tinkoff-optimization-of-procurement/pull/22%23issuecomment-414140653%22%2C%20%22https%3A//github.com/robot-lab/tinkoff-optimization-of-procurement/pull/22%23issuecomment-414140770%22%2C%20%22https%3A//github.com/robot-lab/tinkoff-optimization-of-procurement/pull/22%23issuecomment-414140788%22%2C%20%22https%3A//github.com/robot-lab/tinkoff-optimization-of-procurement/pull/22%23issuecomment-414140998%22%5D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/Vasar007'></a><a href='https://github.com/ptrdiff'></a>

<a href='https://www.codereviewhub.com/robot-lab/tinkoff-optimization-of-procurement/pull/22?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robot-lab/tinkoff-optimization-of-procurement/pull/22?approve=0'></a>&nbsp;<a href='https://github.com/robot-lab/tinkoff-optimization-of-procurement/pull/22'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by ptrdiff** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robot-lab/tinkoff-optimization-of-procurement/pull/22'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by Vasar007** [comment]
:shipit:

**Comment by Vasar007** [comment]
:shipit:

**Comment by ptrdiff** [comment]
:shipit:

**Comment by ptrdiff** [comment]
:shipit:

**Comment by Vasar007** [comment]
👍

**Pull request merged**
